<?php
//includes header+nav
define('TIT1','-Proyectos IES Delgado Hernández');
define('INICIO','Inicio');
define('CURSOS','Cursos');
define('PERFIL','Mi Perfil');
define('INICIO_S','Iniciar Sesion');
define('CERRAR_S','Cerrar Sesion');
define('PANEL','Panel De Control');
define('BIENVM','Bienvenida');
define('BIENVH','Bienvenido');
define('PYP','Planes y proyectos del centro');
define('BUSQ','Buscar...');
define('PHLEMAIL','Introduzca su email');
define('LOGEMAIL','Email');
define('PHLPASS','Introduzca su contraseña');
define('LOGPASS','Contraseña');
define('LOGBUTTON','Acceder');
define('LOGREM','Recuérdame');
define('LOGCAN','Cancelar');
define('LOGFOR','¿Olvidó su');
define('INLOG','Iniciar Sesión');
define('ADDRE','Proyectos añadidos recientemente:');
define('LEER_MAS','Leer más');
define('ACEPTAR','Aceptar');
define('MENSAJE','Este sitio web utiliza cookies para garantizar que obtenga la mejor experiencia en nuestro sitio web.');
define('DIREC', 'Dirección :');
define('CALLE','C/');
define('LOCA','Localidad :');
define('TLF','Teléfono de contacto :');
define('POY','Proyecto');
define('PC','Proyectos del curso ');
define('PC2','');
define('NOMBRE','Nombre : ');
define('APELLIDOS','Apellidos : ');
define('TIPO','Tipo de cuenta : ');
define('ADMIN',' Administrador');
define('PROFE',' Profesor');
define('ALUM',' Alumno');
define('MODPER','Editar Perfil');
define('SEXO','Género : ');
define('HOM','Masculino');
define('MUJ','Femenino');
define('SAV','Guardar');
define('DEL','Eliminar');
define('FOTPER','Foto de Perfil');
define('DATPER','Datos del Usuario');
define('FOTSUB','Foto actualizada correctamente');
define('FOTBOR','Foto borrada correctamente');
define('FOTAFK','No existe foto para borrar');
define('RESCOR','Imagen restaurada correctamente');
define('NOFOT','No existe imagen para restaurar');
define('OLDPASS','Contraseña actual: ');
define('NEWPASS','Nueva contraseña: ');
define('CONFPASS','Confirme contraseña: ');
define('NOPASS','Los tres campos son obligatorios');
define('OLDPASSFAL','La contraseña actual es incorrecta');
define('CONFPASSFAL','Las nuevas contraseñas no coinciden');
define('CHPASS','Contraseña cambiada correctamente');
define('PASSMAIL','Email o Contraseña incorrectos');
define('NOPASSMAIL','Email o Contraseña en blanco');
define('LOCOR','Sesión cerrada correctamente');
define('USUARIOS','Usuarios');
define('PROYECT','Proyectos');
define('AÑADIR_USUARIO','Añadir usuario');
define('MODIFICAR_USUARIO','Modificar usuario');
define('BAJA_USUARIO','Eliminar usuario');
define('AÑADIR_CURSO','Añadir curso');
define('MODIFICAR_CURSO','Modificar curso');
define('BAJA_CURSO','Eliminar curso');
define('AÑADIR_PROYECTO','Añadir proyecto');
define('MODIFICAR_PROYECTO','Modificar proyecto');
define('BAJA_PROYECTO','Eliminar proyecto');
define('ALUMN','Alumno');
define('PRIVI','Privilegio: ');
define('ELIGEPRIVI','Grado de privilegio');
define('NODISP','Email no disponible');
define('SIDISP','Email disponible');
define('PROBAR','Progreso de carga de informacion');
define('GENINFO','Información General');
define('USUGEN','Número de usuarios según Género');
define('USUTIP','Número de usuarios según el tipo de cuenta');
define('HOMS','Hombres');
define('MUJS','Mujeres');
define('PROFES','Profesores');
define('ALUMS','Alumnos');
define('PUBL','Publicación');
define('COOR','Coordinador');
define('ADDCUR','Usuario añadido correctamente');
define('NNMAIL','Debes indicar un Email');
define('PARTI','Ha Participado en');
define('COORD','Coordinador');
define('EDITOR','Editor');
define('DOCBY','Documentado por');
define('SELUSER','Selecciona usuario');
define('USERDEL','Eliminar usuario');
define('MODYES','Modificacion realizada correctamente');
define('SELPROY','Selecciona proyecto');
define('USU2PROY','Añadir usuarios a un proyecto');
define('USUYPROY','Debes seleccionar un proyecto y un alumno');
define('ALUMREP','El alumno ya está incluido en el proyecto seleccionado');
define('USU2PROYOK','Alumno/s agregado al proyecto correctamente');
define('USUDELPROY','Eliminar usuarios de un proyecto');
define('USUDELPROYNO','El alumno no participa en el proyecto');
define('USUDELPROYOK','Alumno/s eliminado del proyecto correctamente');
define('NOPROYECTS','No hay proyectos disponibles');
define('HOLA','Hola ');
define('TPASS','Al crear su cuenta, se estableció como contraseña su propio email, para evitar futuros problemas de seguridad, la primera vez que inicie sesión, deberá cambiar dicha contraseña, recuerde que no puede coincidir con su email');
define('PASSISMAIL','La contraseña no puede coincidir con el email');
define('PROYOK','Proyectos publicados');
define('PROYSTOP','Proyectos pendientes de publicación');
define('PROYEDIT','Editar proyectos');
define('CUR','Curso :');
define('SELCUR','Selecciona curso');
define('CURDEL','Eliminar curso');
define('PROY','Proyecto');
define('EJ','Ej:');
define('PROYDEL','Quitar publicación');
define('BLANCKCOUR','Debes introducir un curso');
define('EXISCOUR','El curso ya existe');
define('INVACOUR','Curso introducido inválido');
define('ADDCUOR','Curso añadido correctamente');
define('USERDELETED','Usuario Borrado correctamente');
define('COURDELETED','Curso Borrado correctamente');
define('USRALT','Usuario dado de alta de nuevo');
//nuevos
define('EXISPROY','Ya existe un proyecto con ese nombre');
define('ADDPROY','Proyecto añadido correctamente');
define('NOMES','Nombre (ES)');
define('NAMES','Nombre (EN)');
define('FOOBL','Todos los campos son obligatorios');
define('DESPUB','EL proyecto ha sido ocultado');
define('DEBCHO','Debes seleccionar un poryecto');
define('CURS','Curso');
define('USRR','Usuario');
define('NONOM','El proyecto ya existe');
define('MODPROYCURR','Proyecto modificado correctamente');
define('ALLFIELDS','Todos los campos con obligatorios');
define('CONSECYEAR','Los años deben ser consecutivos');
define('BLANKCOURSE','Debes rellenar el curso');
define('NODISPCOURSE','Curso no disponible');
//Nuevo desde 16/04
define('CAMNOM','Renombrar proyecto');
define('INTNOM','Introduzca nuevo nombre');
define('DEBEINTNOM','Debe introducir un nombre');
define('PROYNOPUB','No existen proyectos sin publicar');
define('PROYSIPUB','Proyecto publicado correctamente');
define('NOMBREPE','El nombre del proyecto ya existe');
define('TEXT','Redactar artículo');
define('PHOTO','Imágenes');
define('YAPUB','Publicados');
define('NOPUB','No publicados');
define('DROPTEXT','Arrastre imágenes aquí o haga clic para cargar');
//Nuevo desde 20/4
define('PROYP','No existen proyectos publicados');
define('USERSUMA','Añadir aquí:');
define('ADD','Añadir');
define('ADDALL','Añadir todos');
define('MINUS','Quitar');
define('MINUSALL','Quitar todos');
define('ALUMINS','No hay alumnos inscritos en este proyecto');
define('ALUMPAINS','No hay alumnos para inscribir en este proyecto');
define('USUDISP','Disponibles:');
define('PART','Participantes:');
define('USUPAAÑADIR','Se añadirán:');
define('PARTDROP','Se eliminarán:');
define('DELALL','Eliminar todos');
define('DESHALL','Deshacer todo');
define('DESH','Deshacer');
define('NOFILE','Faltan ficheros del proyecto');
//nuevo 28/04
define('ACTCONT','Contenido actual');
define('ESP','Español');
define('ENG','Inglés');
define('SELLENG','Seleccione idioma');
define('NOCONT','No hay contenido disponible');
define('REDART','Redactar artículo');
define('FOTACT','Fotos actuales');
define('NOFOTS','No hay fotos subidas');
define('SUBFOTOS','Subir fotos');
define('DELFOTOS','Eliminar fotos');
define('IMAGEN','Imagen');
define('NAMEFOT','Nombre');
define('SELFOTO','Debes seleccionar una foto');
define('UPFOTO','Foto subida correctamente');
define('DELFOTO','Foto eliminada correctamente');
//Nuevo desde 28/04 migue
define('ESCRIALGO','Introduzca texto a buscar'); 
//nuevo 01/05 dani
define('UPDATETEXT','Texto actualizado correctamente'); 
define('CREATETEXT','Texto añadido correctamente'); 
define('PHOTODEL','Se eliminarán');
//nuevo 05/05 dani
define('NONOMB','Debes introducir un nombre');
define('NOCOMM','Debes introducir un comentario');
define('CACRES','carácteres restantes');
define('EJTEXT','Escriba aquí su comentario (máximo 255 carácteres)');
define('MAKECOM','Publique su comentario');
define('COMMENTS','Comentarios');
define('SAY','dijo');
define('INTNAME','Introduzca nombre');
//nuevo 06/05
define('AUNNOCOM','Aún no hay comentarios. ¡Sé el primero en comentar!');
//nuevo 19/05
define('NOPUBROY','No existen proyectos pendientes de publicación');
define('OTHERS','Otros');

