<?php
//includes header+nav
define('TIT1','-Proyects of IES Delgado Hernández');
define('INICIO','Home');
define('CURSOS','Courses');
define('PERFIL','My Profile');
define('INICIO_S','Login');
define('CERRAR_S','Logout');
define('PANEL','Control Panel');
define('BIENVM','Wellcome');
define('BIENVH','Wellcome');
define('PYP','Plans and projects of center');
define('BUSQ','Search...');
define('PHLEMAIL','Enter your email');
define('LOGEMAIL','Email');
define('PHLPASS','Enter your password');
define('LOGPASS','Password');
define('LOGBUTTON','Login');
define('LOGREM','Remember me');
define('LOGCAN','Cancel');
define('LOGFOR','Forgot your');
define('INLOG','Log in');
define('ADDRE','Recently added projects:');
define('LEER_MAS','Learn more');
define('ACEPTAR','Got it!');
define('MENSAJE','This website uses cookies to ensure you get the best experience on our website.');
define('DIREC', 'Adress :');
define('CALLE','S/');
define('LOCA','City :');
define('TLF','Telephone contact :');
define('POY','Project');
define('PC','');
define('PC2',' course projects');
define('NOMBRE','Name : ');
define('APELLIDOS','Surnames : ');
define('TIPO','Kind of account: ');
define('ADMIN',' Administrator');
define('PROFE',' Teacher');
define('ALUM',' Student');
define('MODPER','Edit Profile');
define('SEXO','Gender : ');
define('HOM','Male');
define('MUJ','Female');
define('SAV','Save');
define('DEL','Delete');
define('FOTPER','Profile Picture');
define('DATPER','User Data');
define('FOTSUB','Photo updated correctly');
define('FOTBOR','Photo deleted correctly');
define('FOTAFK','There is no photo to erase');
define('RESCOR','Image restored correctly');
define('NOFOT','There is no image to restore');
define('OLDPASS','Current password: ');
define('NEWPASS','New password: ');
define('CONFPASS','Confirm password: ');
define('NOPASS','The three fields are mandatory');
define('OLDPASSFAL','The current password is incorrect');
define('CONFPASSFAL','New passwords do not match');
define('CHPASS','Password changed correctly');
define('PASSMAIL','Wrong email or password');
define('NOPASSMAIL','Email or Password blank');
define('LOCOR','Session closed correctly');
define('USUARIOS','Users');
define('PROYECT','Projects');
define('AÑADIR_USUARIO','Add user');
define('MODIFICAR_USUARIO','Modify user');
define('BAJA_USUARIO','Remove user');
define('AÑADIR_CURSO','Add course');
define('MODIFICAR_CURSO','Modify course');
define('BAJA_CURSO','Remove course');
define('AÑADIR_PROYECTO','Add proyect');
define('MODIFICAR_PROYECTO','Modify proyect');
define('BAJA_PROYECTO','Remove proyect');
define('ALUMN','Student');
define('PRIVI','Privilege: ');
define('ELIGEPRIVI','Degree of privilege');
define('NODISP','Email not available');
define('SIDISP','Email available');
define('PROBAR','Progress of information loading');
define('GENINFO','General information');
define('USUGEN','Number of users according to Gender');
define('USUTIP','Number of users according to type of account');
define('HOMS','Men');
define('MUJS','women');
define('PROFES','Teachers');
define('ALUMS','Students');
define('PUBL','Publication');
define('COOR','Coordinator');
define('ADDCUR','User added correctly');
define('NNMAIL','You must indicate an Email');
define('PARTI','He has participated in');
define('COORD','Coordinator');
define('EDITOR','Editor');
define('DOCBY','Documented by');
define('SELUSER','Select user');
define('USERDEL','Remove user');
define('MODYES','Modification made correctly');
define('SELPROY','Select Project');
define('USU2PROY','Add users to a project');
define('USUYPROY','You must select a project and a student');
define('ALUMREP','The student is already included in the selected project');
define('USU2PROYOK','Student/s added to the project correctly');
define('USUDELPROY','Remove users from a project');
define('USUDELPROYNO','The student does not participate in the project');
define('USUDELPROYOK','Student/s removed from the project correctly');
define('NOPROYECTS','No projects available');
define('HOLA','Hi ');
define('TPASS','When we create your account, your own email was established as a password, to avoid future security problems, the first time you log in, you must change that password, remember that it can not match your email');
define('PASSISMAIL','The password can not match the email');
define('PROYOK','Published projects');
define('PROYSTOP','Projects pending publication');
define('PROYEDIT','Edit projects');
define('CUR','    Course :');
define('SELCUR','Select course');
define('CURDEL','Delete course');
define('PROY','Proyect');
define('EJ','Ex:');
define('COORD2PROY','Add coordinator to a project');
define('PROYDEL','Remove publication');
define('BLANCKCOUR','You must enter a course');
define('EXISCOUR','The course already exists');
define('INVACOUR','Course introduced invalid');
define('ADDCUOR','Course added correctly');
define('USERDELETED','User Deleted correctly');
define('COURDELETED','Course Deleted correctly');
define('USRALT','User registered again');
//NUEVO
define('EXISPROY','There is already a project with that name');
define('ADDPROY','Project added correctly');
define('NOMES','Name (ES)');
define('NAMES','Name (EN)');
define('FOOBL','All fields are required');
define('CURS','Course');
define('DESPUB','The project has been hidden');
define('DEBCHO','You must select a project');
define('USRR','User');
define('NONOM','The project already exists');
define('MODPROYCURR','Project modified correctly');
define('ALLFIELDS','All fields with mandatory');
define('BLANKCOURSE','You must complete the course');
define('NODISPCOURSE','Course not available');
define('CONSECYEAR','The years must be consecutive');
//Nuevo desde 16/04
define('CAMNOM','Rename project');
define('INTNOM','Enter new name');
define('DEBEINTNOM','You must enter a name');
define('PROYNOPUB','There are no projects without publishing');
define('PROYSIPUB','Project published correctly');
define('NOMBREPE','The name of the project already exists');
define('TEXT','Write article');
define('PHOTO','Images');
define('YAPUB','Published');
define('NOPUB','Unpublished');
define('DROPTEXT','Drag images here or click to upload');
//Nuevo desde 20/4
define('PROYP','There are no published projects');
define('USERSUMA','Add here:');
define('ADD','Add');
define('ADDALL','Add all');
define('MINUS','Remove');
define('MINUSALL','Remove all');
define('ALUMINS','There are no students enrolled in this project');
define('ALUMPAINS','There are no students to enroll in this project');
define('USUDISP','Available:');
define('PART','Participants:');
define('USUPAAÑADIR','To add:');
define('PARTDROP','To eliminate:');
define('DELALL','Delete all');
define('DESHALL','Undo everything');
define('DESH','Undo');
define('NOFILE','Missing project files');
//nuevo 28/04
define('ACTCONT','Current content');
define('ESP','Spanish');
define('ENG','English');
define('SELLENG','Select a language');
define('NOCONT','Not avaible content');
define('REDART','Write article');
define('FOTACT','Current Photos');
define('NOFOTS','No photos uploaded');
define('SUBFOTOS','Upload photos');
define('DELFOTOS','Delete photos');
define('IMAGEN','Image');
define('NAMEFOT','Name');
define('SELFOTO','You must select a photo');
define('UPFOTO','Photo correctly uploaded');
define('DELFOTO','Photo deleted correctly');
//Nuevo desde 29/04
define('ESCRIALGO','Enter text to search');
//nuevo 01/05 dani
define('UPDATETEXT','Text updated correctly'); 
define('CREATETEXT','Text added correctly');
define('PHOTODEL','To be deleted');
//nuevo 05/05 dani
define('NONOMB','You must enter a name');
define('NOCOMM','You must enter a comment');
define('CACRES','characters remaining');
define('EJTEXT','Write your comment here (maximum 255 characters)');
define('MAKECOM','Post your comment');
define('COMMENTS','Comments');
define('SAY','say');
define('INTNAME','Enter name');
//nuevo 06/05
define('AUNNOCOM','No comments yet. Be the first to comment!');
//nuevo 19/05
define('NOPUBROY','There are no projects pending publication');
define('OTHERS','Others');

